### ISSUE TITLE
Sandbox Value Proposal - Open Source

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/Defense-Unicorns-Culture#10]
# Description
Defense Unicorns values Open Source. We understand that collaboration enables **both** technology and people to advance through mechanisms that silos simply do not.

All Unicorns are enabled and supported to participate in all facets of Open Source behavior. Collaboration through discussions, documentation, education, Issues, culture and even code (Shocking I know). What I want to emphasize here is that Open Source is much more than just code - it's a way of promoting innovation and advancement in positive ways - to include challenging the current direction of an effort through constructive feedback.

## Internal Impact
Advocating Open Source as a value for Defense Unicorns means promoting collaboration to our products across all efforts. This is already being done - Groups are providing value in the forms of reporting issues or fixes to bugs directly. Rather than the days-old "toss it over the wall to the owner" - advocacy here ensures all Unicorns are empowered to challenge and fix inconsistencies with developer and user experiences. 

At its core - collaboration drives progress - It provides new learning and perspectives as experiences and thoughts are shared.

## External Impact
Additionally, promoting collaboration external to our products where value can be realized should be of utmost importance to the company and all members herein. All Unicorns should be supported to use their experiences to educate others in public settings for any given domain. 

The impact for technology is a primary driver. Our products orchestrate many technologies directly and/or can be extended to support new/emerging technologies. As these technologies are stood-up and supported, there will always be improvements that can be made back to the source. Again, more than just code - queries, documentation, issues, design sessions, etc.

## Alignment
Advocacy and practice behind Open Source only further aligns with other company values. Exposure to processes and collaborating on current challenges reinforces a learning mentality - which aligns with **_Focused Learning_**. That collaboration opens people to different perspectives and **_insights_** that might provide feedback in a constructive manner.

## Proposal
Given that Open Source is a cultural phenomenon as much as it is a technological one, I would like to propose adding "Open Source" as a company value, and to drive discussion around why this may or may-not be a good fit for our culture.

**Comment by Racer159** [comment]
Would we want to add `Free And` to Open Source to differentiate from the non-free open source things like the Microsoft CLA (https://opensource.microsoft.com/pdf/microsoft-contribution-license-agreement.pdf)?

(I think that helps to not only show that we are open about collaboration/contribution but also that we encourage others to use their freedom to then build upon and continue to propagate those contributions/ideas)

**Comment by Madeline-UX** [comment]
Linux has a very clear description of the benefits of open source I thought I would drop here:

<img width="1227" alt="Screen Shot 2022-07-20 at 3 25 19 PM" src="https://user-images.githubusercontent.com/92826525/180075965-f5fcd590-ad84-4d7c-abb2-725ad1324181.png">
.

**Comment by ntwkninja** [comment]
I am very passionate about the topic of `Convergence'. Breaking down silos and working together toward a common goal. I believe it could be a little broader in application and would like to submit convergence as a potential candidate for the name of the value if it captures all of the above.

**Comment by brandtkeller** [comment]
> Would we want to add `Free And` to Open Source to differentiate from the non-free open source things like the Microsoft CLA (https://opensource.microsoft.com/pdf/microsoft-contribution-license-agreement.pdf)?
> 
> (I think that helps to not only show that we are open about collaboration/contribution but also that we encourage others to use their freedom to then build upon and continue to propagate those contributions/ideas)

@Racer159 I agree - this also further aligns with the company vision 

> A free and secure world that enables progress and innovation.

**Comment by brandtkeller** [comment]
> I am very passionate about the topic of `Convergence'. Breaking down silos and working together toward a common goal. I believe it could be a little broader in application and would like to submit convergence as a potential candidate for the name of the value if it captures all of the above.

@ntwkninja I would love to hash on this. I agree with taking a step back and considering broader terminology. I do want to ensure that we don't obscure the intent of the value by making it too broad. 

IE when we say "Defense Unicorns values _____" I don't want us to have to explain the value - I want the value to speak for itself.

**Comment by ntwkninja** [comment]
Great addition. This is now one of our three uniques as an organization. You guys rock!
