### ISSUE TITLE
private link in public repo

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/Defense-Unicorns-Culture#11]
https://github.com/leapfrogai/Strategic-Growth-/projects/1 is a private board, but this repo is public. External readers will see a 404 error.

Is there a different link we can use, or just describe it rather than link to it? Or just add a note saying the link is to an internal board.

**Comment by RothAndrew** [comment]
Ref: https://github.com/defenseunicorns/Defense-Unicorns-Culture/blob/77206e93500395576a76f7e7f551bf36c0aca54d/README.md?plain=1#L43

**Comment by ntwkninja** [comment]
closing as stale (the link appears to be gone)
