### ISSUE TITLE
Company Values don't capture building simple and beautiful products

### ISSUE THREAD

**Issue by unicornbunny182** [defenseunicorns/Defense-Unicorns-Culture#13]
I think we are missing some type of value around building amazing and simple products. What comes to my mind are three companies, SpaceX, Apple, and Pixar

For Apple, I like this quote from Tim Cook
https://alvinalexander.com/blog/post/mac-os-x/apple-business-philosophy-mission-statement/

For SpaceX, I like the Elon Algorithm
https://insideevs.com/news/526954/elon-musk-5-steps-success/

For Pixar, it is in their company values, specifically "Quality is the best business plan" 
https://www.fearlessculture.design/blog-posts/pixar-culture-design-canvas

I don't think we capture the importance of developing simple and amazing products in our current company values and would like to discuss how to "fix" this gap.

**Comment by MaggieFrances** [comment]
Discussed with Rob and Gabe. Velocity is getting closer. Closing the issue.
